// ──────────────────────────────────────────────
// Complaint text generator — English + Hindi
// ──────────────────────────────────────────────
import { DEPARTMENTS } from "../config";

// ── English ───────────────────────────────────
export function buildComplaintText({ label, areaName, landmark, confidence, dateTime }) {
  const dept = DEPARTMENTS[label];
  const landmarkLine = landmark ? `\nLandmark / Additional info: ${landmark}` : "";
  const confidencePct = Math.round(confidence * 100);

  return `To: ${dept.name}
Subject: Civic Issue Report — ${label} at ${areaName}

Dear Sir/Madam,

I am writing to report a civic issue in my area. Details are as follows:

  Issue type   : ${label}
  Location     : ${areaName}, Delhi${landmarkLine}
  Date & Time  : ${dateTime}
  AI Confidence: ${confidencePct}%

I request that this issue be looked into.

This report was generated by the FixMyDelhi demo app.

Regards,
A Delhi Resident`;
}

// ── Hindi label map ───────────────────────────
const HINDI_ISSUE = {
  "Pothole":      "सड़क में गड्ढा",
  "Garbage dump": "कूड़े का ढेर",
  "Waterlogging": "जलभराव",
  "Normal road":  "सामान्य सड़क",
};

const HINDI_DEPT = {
  "Pothole":      "Demo Roads Dept",
  "Garbage dump": "Demo Sanitation Dept",
  "Waterlogging": "Demo Drainage Dept",
};

// ── Hindi ─────────────────────────────────────
export function buildComplaintTextHindi({ label, areaName, landmark, confidence, dateTime }) {
  const dept = DEPARTMENTS[label];
  const hindiIssue = HINDI_ISSUE[label] || label;
  const hindiDept  = HINDI_DEPT[label]  || dept.name;
  const landmarkLine = landmark ? `\nस्थल-चिह्न / अतिरिक्त जानकारी: ${landmark}` : "";
  const confidencePct = Math.round(confidence * 100);

  return `सेवा में,
${hindiDept}

विषय: नागरिक समस्या — ${areaName} में ${hindiIssue}

महोदय/महोदया,

हमारे क्षेत्र में एक नागरिक समस्या उत्पन्न हुई है। विवरण निम्नलिखित है:

  समस्या का प्रकार : ${hindiIssue}
  स्थान            : ${areaName}, दिल्ली${landmarkLine}
  दिनांक व समय    : ${dateTime}
  AI सटीकता        : ${confidencePct}%

कृपया इस समस्या का शीघ्र समाधान करें।

यह शिकायत FixMyDelhi डेमो ऐप के माध्यम से उत्पन्न की गई है।

सादर,
एक दिल्ली निवासी`;
}
